### ISSUE TITLE
Make it possible to parse rST with the parser

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-Parser#126] opened 2020-04-13 20:01 UTC
I ran into a challenge in trying to set up the `sphinx_click` extension in the docs. That extension provides a directive that *generates* other directives hard-coded in rST. I wonder if, for these kinds of cases where rST is hard-coded, we could have something like an `{rst}` directive that uses the Sphinx rST parser instead of our markdown parser.

**Comment by chrisjsewell** [comment] 2020-04-14 16:11
possibly??? Yeh they definitely haven't written that extension in the "ideal" way lol!
I'd want to give this further thought, before rushing into anything that further complicates the syntax, but yeh its a possibility

**Comment by choldgraf** [comment] 2020-04-14 17:59
After thinking about it a bit more, I am tempted to say that if people want to use an extension that *only* supports rST, then they should just write their page in rST since both rST and markdown work equally well. That's [what I ended up doing in the CLI](https://github.com/ExecutableBookProject/cli/blob/master/docs/start/cli.rst) and I think it will be fine as long as there's not some super-important package that non-power users need.

**Comment by chrisjsewell** [comment] 2020-07-20 22:34
duplicate of #164

**Closed by chrisjsewell** 2020-07-20 22:34 UTC
Labels: enhancement
