### ISSUE TITLE
This line in setup.py causes a failure when installing myst-parser with Sphinx 4.0.2

### ISSUE THREAD

**Issue by kitanata** [executablebooks/MyST-Parser#381] opened 2021-05-20 20:40 UTC
https://github.com/executablebooks/MyST-Parser/blob/a39d2363a161b7f1d4427c6f3011203b560cb302/setup.cfg#L45

**Comment by chrisjsewell** [comment] 2021-05-20 20:44
Heya this is duplicate of #378 will be fixed soon 😀

**Closed by chrisjsewell** 2021-05-20 20:44 UTC
