### ISSUE TITLE
Looks like Mermaid Diagrams are now working?

### ISSUE THREAD

**Issue by Belmogodx** [executablebooks/MyST-Parser#727] opened 2023-02-28 20:01 UTC
### Describe the bug

**context**
Mermaid diagrams do not seem to work anymore in sphinx generated documents

**expectation**
I expect a mermaid diagram to work when wrapped in braces ex: {mermaid} 

**bug**
look at the get started section of the documentation, mermaid diagram is no longer working 
https://myst-parser.readthedocs.io/en/latest/intro.html

**problem**
This is a problem for people doing documentation with myst parser because mermaid diagrams do not render anymore

### Reproduce the bug

build documentation with sphinx that includes mermaid diagrams

### List your environment

myst-parser 0.17.0
sphinx contrib mermaid 0.7.1

**Comment by chrisjsewell** [comment] 2023-02-28 20:03
Thanks for the feedback, but duplicate of #725

**Comment by Belmogodx** [comment] 2023-02-28 20:59
@chrisjsewell these diagrams used to work, can i revert back to old packages to fix this?

**Closed** 2023-02-28 20:58 UTC
Labels: bug

**Comment by chrisjsewell** [comment] 2023-02-28 21:01
They still do work, it's just a typo in the documentation
