### ISSUE TITLE
Issue on page /syntax/admonitions.html - In example, class should be space separated not comma

### ISSUE THREAD

**Issue by 72757373656c6c** [executablebooks/MyST-Parser#902] opened 2024-04-07 20:19 UTC
On the [Admonition](https://myst-parser.readthedocs.io/en/latest/syntax/admonitions.html) webpage, in the first section titled "Admonition Types", the example is incorrect. 

The text for **class** is correct, but the example is not. The text says the class is a **space** separated list, but the example shows a **comma** separated list.

**Text above example and the example**

```
These admonitions take no argument, but may be specified with options:

class:  A space-separated list of CSS classes to add to the admonition. 
name:   A reference target for the admonition (see cross-referencing).

:::{tip}
:class: myclass1,myclass2 
:name: a-tip-reference
Let's give readers a helpful hint!
:::

[Reference to my tip](#a-tip-reference)
```

**HTML Output**

Space separated:

```
<div class="myclass1 myclass2 admonition tip" id="a-tip-reference"
```

Common separated:

```
<div class="myclass1-myclass2 admonition tip" id="a-tip-reference">
```

**Comment by dbitouze** [comment] 2024-04-07 20:21
Duplicate of #809?

**Closed as completed** 2024-04-07 20:53 UTC

**Comment by chrisjsewell** [comment] 2024-04-07 20:55
Even better, if you want to create a PR to fix it 😄
