### ISSUE TITLE
Support for all-pages-on-site epilog and prolog

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/MyST-Parser#270] opened 2020-11-13 19:58 UTC
**Is your feature request related to a problem? Please describe.**

Sphinx allows appending/pre-pending to sources of a ReStructuredText file, using the `rst_epilog` and `rst_prolog` attributes in `conf.py`. This is especially useful for HTML meta tags, that are shared across the site.

**Describe the solution you'd like**

Replicate https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-rst_epilog, but as `md_epilog`.

**Describe alternatives you've considered**

None. I think this'll be really nice to have.

**Additional context**

See https://github.com/pradyunsg/furo/issues/31 for what chain of events led me to file this issue.

**Comment by chrisjsewell** [comment] 2020-12-17 16:10
this is a duplicate of #190, I will explain there how #273 goes some way to addressing this

**Closed by chrisjsewell** 2020-12-17 16:10 UTC
Labels: enhancement
