### ISSUE TITLE
Wrong rendering of '**foo**

### ISSUE THREAD

**Issue by davidbrochart** [executablebooks/MyST-Parser#439] opened 2021-10-12 14:16 UTC
### Describe the problem

I'm not sure this is the right place, but I have noticed an issue where `'**foo**` is rendered in HTML as ”**foo**, but `’**foo**` is fine (rendered as ’**foo**).

### Steps to reproduce

1. Write a markdown file that has `'**foo** ’**foo**`.
2. Render to HTML.
3. Observe the HTML rendered as: ”**foo** ’**foo**

**Comment by davidbrochart** [comment] 2021-10-12 16:37
I think the repo is private, so I can't point you to it, but maybe @nthiery or @SylvainCorlay can provide more information?

**Comment by chrisjsewell** [comment] 2021-12-05 02:26
Heya, I have indeed reproduced this, by setting the language to `fr`, and also exactly the same happens in `.rst` files.
So this is part of sphinx's translation mechanism.

I'm going to close this here then, if thats ok, since I don't think it is anything that myst-parser can affect.
I would suggest maybe opening an issue on https://github.com/sphinx-doc/sphinx if you feel this is incorrect.

Obviously feel free to re-open, if they show that it is a bug in myst-parser thanks

**Closed by chrisjsewell** 2021-12-05 02:26 UTC
Labels: bug
