### ISSUE TITLE
MyST tables break Sphinx Texinfo output

### ISSUE THREAD

**Issue by Jean-Abou-Samra** [executablebooks/MyST-Parser#567] opened 2022-05-14 20:30 UTC
### Describe the bug

When the MyST document contains a table, `make info` errors out:

```
Exception occurred:
  File "/home/jean/.local/lib/python3.10/site-packages/sphinx/writers/texinfo.py", line 1014, in visit_colspec
    self.body.append('{%s} ' % ('x' * (n + 2)))
TypeError: can't multiply sequence by non-int of type 'float'
```

At a glance, I see that myst_parser does this in `base.py` line 916:

```
        colwidths = [round(100 / maxcols, 2)] * maxcols
```

Yet, Sphinx's Texinfo writer expects column widths to be integers.

### Reproduce the bug

`conf.py`:

```
extensions = ["myst_parser"]
```

`index.md`:

```
| foo | bar |
| --- | --- |
| baz | bim |
```

Command:

```
sphinx-build -M info . build
```

**Comment by chrisjsewell** [comment] 2022-05-14 21:19
Thanks for the report, although this is a duplicate of #540

**Closed** 2022-05-14 21:19 UTC
Labels: bug

**Comment by Jean-Abou-Samra** [comment] 2022-05-14 21:25
Oops, sorry, I thought I had searched more carefully.
